2024-02-09 10:35:04.804521: I external/local_tsl/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
2024-02-09 10:35:05.282812: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-02-09 10:35:05.283505: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-02-09 10:35:05.374516: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-02-09 10:35:05.570747: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-02-09 10:35:07.845932: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Map:   0%|          | 0/14589 [00:00<?, ? examples/s]Map:   8%|▊         | 1227/14589 [00:00<00:01, 12200.29 examples/s]Map:  19%|█▉        | 2789/14589 [00:00<00:00, 12859.54 examples/s]Map:  34%|███▍      | 4937/14589 [00:00<00:00, 13235.28 examples/s]Map:  47%|████▋     | 6923/14589 [00:00<00:00, 13231.72 examples/s]Map:  61%|██████    | 8916/14589 [00:00<00:00, 13178.07 examples/s]Map:  73%|███████▎  | 10604/14589 [00:00<00:00, 9240.67 examples/s]Map:  82%|████████▏ | 12000/14589 [00:01<00:00, 9903.84 examples/s]Map:  93%|█████████▎| 13509/14589 [00:01<00:00, 11015.25 examples/s]Map: 100%|██████████| 14589/14589 [00:01<00:00, 11262.52 examples/s]
Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]Loading checkpoint shards:  50%|█████     | 1/2 [00:11<00:11, 11.10s/it]Loading checkpoint shards: 100%|██████████| 2/2 [00:16<00:00,  7.62s/it]Loading checkpoint shards: 100%|██████████| 2/2 [00:16<00:00,  8.14s/it]
  0%|          | 0/456 [00:00<?, ?it/s]  0%|          | 1/456 [00:20<2:34:00, 20.31s/it]  0%|          | 2/456 [00:37<2:19:54, 18.49s/it]  1%|          | 3/456 [00:55<2:17:14, 18.18s/it]  1%|          | 4/456 [01:12<2:14:01, 17.79s/it]  1%|          | 5/456 [01:30<2:13:02, 17.70s/it]  1%|▏         | 6/456 [01:47<2:11:35, 17.55s/it]  2%|▏         | 7/456 [02:04<2:10:38, 17.46s/it]  2%|▏         | 8/456 [02:22<2:10:33, 17.49s/it]  2%|▏         | 9/456 [02:38<2:08:27, 17.24s/it]  2%|▏         | 9/456 [02:38<2:11:29, 17.65s/it]
Traceback (most recent call last):
  File "/home/abdelrahman.sadallah/mambaforge/envs/nlp/lib/python3.10/site-packages/torch/utils/data/_utils/collate.py", line 127, in collate
    return elem_type({key: collate([d[key] for d in batch], collate_fn_map=collate_fn_map) for key in elem})
  File "/home/abdelrahman.sadallah/mambaforge/envs/nlp/lib/python3.10/site-packages/torch/utils/data/_utils/collate.py", line 127, in <dictcomp>
    return elem_type({key: collate([d[key] for d in batch], collate_fn_map=collate_fn_map) for key in elem})
  File "/home/abdelrahman.sadallah/mambaforge/envs/nlp/lib/python3.10/site-packages/torch/utils/data/_utils/collate.py", line 150, in collate
    raise TypeError(default_collate_err_msg_format.format(elem_type))
TypeError: default_collate: batch must contain tensors, numpy arrays, numbers, dicts or lists; found <class 'NoneType'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/abdelrahman.sadallah/mbzuai/decrypting-crosswords/llms/evaluate_llm.py", line 130, in <module>
    for batch in tqdm(val_dataloader):
  File "/home/abdelrahman.sadallah/mambaforge/envs/nlp/lib/python3.10/site-packages/tqdm/std.py", line 1182, in __iter__
    for obj in iterable:
  File "/home/abdelrahman.sadallah/mambaforge/envs/nlp/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 633, in __next__
    data = self._next_data()
  File "/home/abdelrahman.sadallah/mambaforge/envs/nlp/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 677, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/abdelrahman.sadallah/mambaforge/envs/nlp/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 54, in fetch
    return self.collate_fn(data)
  File "/home/abdelrahman.sadallah/mambaforge/envs/nlp/lib/python3.10/site-packages/torch/utils/data/_utils/collate.py", line 265, in default_collate
    return collate(batch, collate_fn_map=default_collate_fn_map)
  File "/home/abdelrahman.sadallah/mambaforge/envs/nlp/lib/python3.10/site-packages/torch/utils/data/_utils/collate.py", line 130, in collate
    return {key: collate([d[key] for d in batch], collate_fn_map=collate_fn_map) for key in elem}
  File "/home/abdelrahman.sadallah/mambaforge/envs/nlp/lib/python3.10/site-packages/torch/utils/data/_utils/collate.py", line 130, in <dictcomp>
    return {key: collate([d[key] for d in batch], collate_fn_map=collate_fn_map) for key in elem}
  File "/home/abdelrahman.sadallah/mambaforge/envs/nlp/lib/python3.10/site-packages/torch/utils/data/_utils/collate.py", line 150, in collate
    raise TypeError(default_collate_err_msg_format.format(elem_type))
TypeError: default_collate: batch must contain tensors, numpy arrays, numbers, dicts or lists; found <class 'NoneType'>
